sudo: false

os:
 - linux
 - osx

branches:
  only:
    - "master"

language: node_js
dist: bionic
services:
  - xvfb

node_js:
  - 12

env:
  - CODE_VERSION=1.37.0
  - CODE_VERSION=1.39.0
  - CODE_VERSION=1.40.0
  - CODE_VERSION=latest

install:
  - npm install
  - npm run build

before_script:
  - npm run prepare-test

script:
  - npm run ci-test