sudo: false

language: node_js
dist: bionic
services:
  - xvfb

node_js:
  - 11

before_install:
 - sudo apt-get -y install libxtst-dev libpng++-dev

install:
  - npm install
  - npm run build

before_script:
  - npm run prepare-test

script:
  - npm test